name: Run Rsfrac online

on:
  workflow_dispatch

jobs:
  run-online:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Install system dependencies
        run: sudo apt-get install -y curl libgmp-dev libmpfr-dev libmpc-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Rsfrac
        run: cargo install --path . --features web-runner
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install textual-web
      - run: textual-web --config ganglion.toml

